// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2V8jF0UhWAX6Q_ObCegjfZlX_kiJW4KM',
    appId: '1:206112169695:web:c3796d850c77f12678136a',
    messagingSenderId: '206112169695',
    projectId: 'hasani-payroll',
    authDomain: 'hasani-payroll.firebaseapp.com',
    storageBucket: 'hasani-payroll.firebasestorage.app',
    measurementId: 'G-XRMP5S4Y8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67LK_uVKssT1jDS3pOCAoHuus45w_pv8',
    appId: '1:206112169695:android:cf4473f08c515a8278136a',
    messagingSenderId: '206112169695',
    projectId: 'hasani-payroll',
    storageBucket: 'hasani-payroll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2b4VLtVr1bJJM3SQdR0Wgo6TM1x8cPi8',
    appId: '1:206112169695:ios:21e312f76e63ba0678136a',
    messagingSenderId: '206112169695',
    projectId: 'hasani-payroll',
    storageBucket: 'hasani-payroll.firebasestorage.app',
    iosBundleId: 'com.example.hasaniPayrollPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2b4VLtVr1bJJM3SQdR0Wgo6TM1x8cPi8',
    appId: '1:206112169695:ios:21e312f76e63ba0678136a',
    messagingSenderId: '206112169695',
    projectId: 'hasani-payroll',
    storageBucket: 'hasani-payroll.firebasestorage.app',
    iosBundleId: 'com.example.hasaniPayrollPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2V8jF0UhWAX6Q_ObCegjfZlX_kiJW4KM',
    appId: '1:206112169695:web:2d7f1dd004d5fb7e78136a',
    messagingSenderId: '206112169695',
    projectId: 'hasani-payroll',
    authDomain: 'hasani-payroll.firebaseapp.com',
    storageBucket: 'hasani-payroll.firebasestorage.app',
    measurementId: 'G-J1VRS275B6',
  );
}
